[package]
name = "fairy"
version = "0.1.0"
edition = "2021"

[dependencies]
arrayvec = "*"
rand = "0.8"
derive_rand = { path = "derive_rand" }

[dev-dependencies]
criterion = "0.4"

[[bench]]
name = "tablebase"
harness = false
